server:
  port: 8200
#逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 #删除的值
      logic-not-delete-value: 0 #未删除的值
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ylservice?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  #规定后端返回到前端页面的时间格式 否则返回的会是0区 即格林威治时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #关闭模板引擎缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
#开启sql打印
#logging:
#  level:
#    root: DEBUG